language: swift
osx_image: xcode8.3
before_script:
  - pod lib lint --verbose --fail-fast
  - pod repo update
script:
  - cd TimeZonePickerExample && pod install
  - xcodebuild -workspace TimeZonePickerExample.xcworkspace -scheme TimeZonePickerExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
